baseURL = 'https://valdokl-gomes.github.io/meu-blog-de-anime/'
defaultContentLanguage = 'pt-br'
title = 'Meu Blog de Anime'
theme = 'ananke'
[params]
  # Força o tema a aceitar links externos como imagens de destaque
  featured_image = "" 
  # Se houver uma seção [markup], garanta que ela permita HTML nas imagens
[markup.goldmark.renderer]
  unsafe = true
