baseURL = 'https://valdokl-gomes.github.io/meu-blog-de-anime/'
defaultContentLanguage = 'pt-br'
title = 'Meu Blog de Anime'
theme = 'ananke'

[params]
  featured_image = ""
  disqusShortname = 'seu-nome-do-disqus'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
